// Vocabulario Unité 4 — La protection animale
// Extraído de la ficha del aula

const VOCAB = [
  // ANIMAUX
  { fr: "un âne",          es: "un burro",        cat: "animaux" },
  { fr: "une chèvre",      es: "una cabra",       cat: "animaux" },
  { fr: "une poule",       es: "una gallina",     cat: "animaux" },
  { fr: "un coq",          es: "un gallo",        cat: "animaux" },
  { fr: "un hibou",        es: "un búho",         cat: "animaux" },
  { fr: "un loup",         es: "un lobo",         cat: "animaux" },
  { fr: "un moustique",    es: "un mosquito",     cat: "animaux" },
  { fr: "un mouton",       es: "una oveja",       cat: "animaux" },
  { fr: "un canard",       es: "un pato",         cat: "animaux" },
  { fr: "une grenouille",  es: "una rana",        cat: "animaux" },
  { fr: "un serpent",      es: "una serpiente",   cat: "animaux" },
  { fr: "un kangourou",    es: "un canguro",      cat: "animaux" },
  { fr: "une abeille",     es: "una abeja",       cat: "animaux" },
  { fr: "un perroquet",    es: "un loro",         cat: "animaux" },
  { fr: "un cheval",       es: "un caballo",      cat: "animaux" },
  { fr: "une vache",       es: "una vaca",        cat: "animaux" },
  { fr: "un lapin",        es: "un conejo",       cat: "animaux" },
  { fr: "un crocodile",    es: "un cocodrilo",    cat: "animaux" },
  { fr: "un zèbre",        es: "una cebra",       cat: "animaux" },
  { fr: "un hippopotame",  es: "un hipopótamo",   cat: "animaux" },
  { fr: "un singe",        es: "un mono",         cat: "animaux" },
  { fr: "un papillon",     es: "una mariposa",    cat: "animaux" },
  { fr: "une girafe",      es: "una jirafa",      cat: "animaux" },
  { fr: "un éléphant",     es: "un elefante",     cat: "animaux" },
  { fr: "un gorille",      es: "un gorila",       cat: "animaux" },
  { fr: "un rhinocéros",   es: "un rinoceronte",  cat: "animaux" },
  { fr: "un ours",         es: "un oso",          cat: "animaux" },
  { fr: "un oiseau",       es: "un pájaro",       cat: "animaux" },
  { fr: "un dauphin",      es: "un delfín",       cat: "animaux" },
  { fr: "une baleine",     es: "una ballena",     cat: "animaux" },
  { fr: "un requin",       es: "un tiburón",      cat: "animaux" },
  { fr: "une pieuvre",     es: "un pulpo",        cat: "animaux" },
  { fr: "une crevette",    es: "una gamba",       cat: "animaux" },
  { fr: "un crabe",        es: "un cangrejo",     cat: "animaux" },

  // VERBES
  { fr: "nourrir",            es: "alimentar",         cat: "verbes" },
  { fr: "adopter",            es: "adoptar",           cat: "verbes" },
  { fr: "sensibiliser",       es: "concienciar",       cat: "verbes" },
  { fr: "agir",               es: "actuar",            cat: "verbes" },
  { fr: "traiter",            es: "tratar",            cat: "verbes" },
  { fr: "soigner",            es: "cuidar / curar",    cat: "verbes" },
  { fr: "faire un don",       es: "hacer una donación",cat: "verbes" },
  { fr: "hydrater",           es: "hidratar",          cat: "verbes" },
  { fr: "lutter contre",      es: "luchar contra",     cat: "verbes" },
  { fr: "protéger",           es: "proteger",          cat: "verbes" },
  { fr: "élever",             es: "criar",             cat: "verbes" },
  { fr: "ramasser les excréments", es: "recoger los excrementos", cat: "verbes" },
  { fr: "maltraiter",         es: "maltratar",         cat: "verbes" },
  { fr: "abandonner",         es: "abandonar",         cat: "verbes" },
  { fr: "battre",             es: "pegar (a un animal)", cat: "verbes" },
  { fr: "souffrir",           es: "sufrir",            cat: "verbes" },
  { fr: "s'occuper",          es: "ocuparse de",       cat: "verbes" },
  { fr: "recueillir",         es: "recoger (animales)",cat: "verbes" },
  { fr: "désinfecter",        es: "desinfectar",       cat: "verbes" },
  { fr: "sauver",             es: "salvar",            cat: "verbes" },
  { fr: "contrôler",          es: "controlar",         cat: "verbes" },
  { fr: "interdire",          es: "prohibir",          cat: "verbes" },
  { fr: "éduquer",            es: "educar",            cat: "verbes" },
  { fr: "caresser",           es: "acariciar",         cat: "verbes" },
  { fr: "changer la litière", es: "cambiar la arena",  cat: "verbes" },

  // PROTECTION ANIMALE (vocabulario)
  { fr: "le droit des animaux", es: "el derecho de los animales", cat: "protection" },
  { fr: "une expérience",       es: "un experimento",  cat: "protection" },
  { fr: "le bien-être animal",  es: "el bienestar (animal)", cat: "protection" },
  { fr: "la maltraitance",      es: "el maltrato",     cat: "protection" },
  { fr: "l'abandon",            es: "el abandono",     cat: "protection" },
  { fr: "la souffrance",        es: "el sufrimiento",  cat: "protection" },
  { fr: "la tristesse",         es: "la tristeza",     cat: "protection" },
  { fr: "un refuge",            es: "un refugio",      cat: "protection" },
  { fr: "un éleveur / une éleveuse", es: "un criador / una criadora", cat: "protection" },
  { fr: "l'affection",          es: "el afecto",       cat: "protection" },
  { fr: "la préservation",      es: "la preservación", cat: "protection" },
  { fr: "la protection",        es: "la protección",   cat: "protection" },
  { fr: "la disparition",       es: "la desaparición", cat: "protection" },
  { fr: "il est urgent de + inf", es: "es urgente + hacer", cat: "protection" },
  { fr: "un bénévole",          es: "un voluntario",   cat: "protection" },
  { fr: "une norme",            es: "una norma",       cat: "protection" },
  { fr: "la biodiversité",      es: "la biodiversidad",cat: "protection" },
  { fr: "la présence",          es: "la presencia",    cat: "protection" },
  { fr: "une obligation",       es: "una obligación",  cat: "protection" },
  { fr: "l'hygiène",            es: "la higiene",      cat: "protection" },
  { fr: "l'alimentation",       es: "la alimentación", cat: "protection" },
  { fr: "une puce",             es: "un chip / una pulga", cat: "protection" },
  { fr: "un vaccin",            es: "una vacuna",      cat: "protection" },
  { fr: "un parasite",          es: "un parásito",     cat: "protection" },
  { fr: "être désorienté",      es: "estar desorientado", cat: "protection" },
  { fr: "être capable de",      es: "ser capaz de",    cat: "protection" },
  { fr: "être joueur",          es: "ser juguetón",    cat: "protection" },
  { fr: "être câlin / affectueux", es: "ser afectuoso", cat: "protection" },
];

// Subjonctif présent — verbos irregulares frecuentes
const SUBJ_IRREGULAR = [
  { inf: "être",   forms: ["sois", "sois", "soit", "soyons", "soyez", "soient"] },
  { inf: "avoir",  forms: ["aie", "aies", "ait", "ayons", "ayez", "aient"] },
  { inf: "aller",  forms: ["aille", "ailles", "aille", "allions", "alliez", "aillent"] },
  { inf: "faire",  forms: ["fasse", "fasses", "fasse", "fassions", "fassiez", "fassent"] },
  { inf: "pouvoir",forms: ["puisse", "puisses", "puisse", "puissions", "puissiez", "puissent"] },
  { inf: "savoir", forms: ["sache", "saches", "sache", "sachions", "sachiez", "sachent"] },
  { inf: "vouloir",forms: ["veuille", "veuilles", "veuille", "voulions", "vouliez", "veuillent"] },
  { inf: "venir",  forms: ["vienne", "viennes", "vienne", "venions", "veniez", "viennent"] },
  { inf: "prendre",forms: ["prenne", "prennes", "prenne", "prenions", "preniez", "prennent"] },
  { inf: "voir",   forms: ["voie", "voies", "voie", "voyions", "voyiez", "voient"] },
  { inf: "boire",  forms: ["boive", "boives", "boive", "buvions", "buviez", "boivent"] },
  { inf: "devoir", forms: ["doive", "doives", "doive", "devions", "deviez", "doivent"] },
  { inf: "falloir",forms: ["—", "—", "faille", "—", "—", "—"] },
];

// Verbos regulares para práctica de conjugación
const SUBJ_REGULAR = [
  { inf: "parler",   forms: ["parle", "parles", "parle", "parlions", "parliez", "parlent"] },
  { inf: "protéger", forms: ["protège", "protèges", "protège", "protégions", "protégiez", "protègent"] },
  { inf: "adopter",  forms: ["adopte", "adoptes", "adopte", "adoptions", "adoptiez", "adoptent"] },
  { inf: "soigner",  forms: ["soigne", "soignes", "soigne", "soignions", "soigniez", "soignent"] },
  { inf: "agir",     forms: ["agisse", "agisses", "agisse", "agissions", "agissiez", "agissent"] },
  { inf: "finir",    forms: ["finisse", "finisses", "finisse", "finissions", "finissiez", "finissent"] },
  { inf: "nourrir",  forms: ["nourrisse", "nourrisses", "nourrisse", "nourrissions", "nourrissiez", "nourrissent"] },
  { inf: "sauver",   forms: ["sauve", "sauves", "sauve", "sauvions", "sauviez", "sauvent"] },
  { inf: "éduquer",  forms: ["éduque", "éduques", "éduque", "éduquions", "éduquiez", "éduquent"] },
  { inf: "interdire",forms: ["interdise", "interdises", "interdise", "interdisions", "interdisiez", "interdisent"] },
  { inf: "vendre",   forms: ["vende", "vendes", "vende", "vendions", "vendiez", "vendent"] },
  { inf: "écrire",   forms: ["écrive", "écrives", "écrive", "écrivions", "écriviez", "écrivent"] },
];

const SUBJ_PRONOUNS = ["je", "tu", "il/elle", "nous", "vous", "ils/elles"];

// Presente de indicativo — necesario para construir el subjonctif
// (radical = "ils" sin -ent; nous/vous = radical alternativo en verbos con cambio).
// Agrupado por familias para enseñar el patrón.
const INDIC_PRESENT = {
  regulares_er: [
    { inf: "parler",  forms: ["parle", "parles", "parle", "parlons", "parlez", "parlent"] },
    { inf: "adopter", forms: ["adopte", "adoptes", "adopte", "adoptons", "adoptez", "adoptent"] },
    { inf: "soigner", forms: ["soigne", "soignes", "soigne", "soignons", "soignez", "soignent"] },
    { inf: "sauver",  forms: ["sauve", "sauves", "sauve", "sauvons", "sauvez", "sauvent"] },
    { inf: "éduquer", forms: ["éduque", "éduques", "éduque", "éduquons", "éduquez", "éduquent"] },
    { inf: "donner",  forms: ["donne", "donnes", "donne", "donnons", "donnez", "donnent"] },
  ],
  regulares_ir: [
    { inf: "finir",    forms: ["finis", "finis", "finit", "finissons", "finissez", "finissent"] },
    { inf: "agir",     forms: ["agis", "agis", "agit", "agissons", "agissez", "agissent"] },
    { inf: "nourrir",  forms: ["nourris", "nourris", "nourrit", "nourrissons", "nourrissez", "nourrissent"] },
    { inf: "réussir",  forms: ["réussis", "réussis", "réussit", "réussissons", "réussissez", "réussissent"] },
    { inf: "choisir",  forms: ["choisis", "choisis", "choisit", "choisissons", "choisissez", "choisissent"] },
  ],
  regulares_re: [
    { inf: "vendre",   forms: ["vends", "vends", "vend", "vendons", "vendez", "vendent"] },
    { inf: "attendre", forms: ["attends", "attends", "attend", "attendons", "attendez", "attendent"] },
    { inf: "répondre", forms: ["réponds", "réponds", "répond", "répondons", "répondez", "répondent"] },
    { inf: "perdre",   forms: ["perds", "perds", "perd", "perdons", "perdez", "perdent"] },
  ],
  // Verbos con doble radical (cambio entre singular/3pl y nous/vous)
  doble_radical: [
    { inf: "prendre",  forms: ["prends", "prends", "prend", "prenons", "prenez", "prennent"] },
    { inf: "venir",    forms: ["viens", "viens", "vient", "venons", "venez", "viennent"] },
    { inf: "tenir",    forms: ["tiens", "tiens", "tient", "tenons", "tenez", "tiennent"] },
    { inf: "boire",    forms: ["bois", "bois", "boit", "buvons", "buvez", "boivent"] },
    { inf: "devoir",   forms: ["dois", "dois", "doit", "devons", "devez", "doivent"] },
    { inf: "voir",     forms: ["vois", "vois", "voit", "voyons", "voyez", "voient"] },
    { inf: "recevoir", forms: ["reçois", "reçois", "reçoit", "recevons", "recevez", "reçoivent"] },
    { inf: "mourir",   forms: ["meurs", "meurs", "meurt", "mourons", "mourez", "meurent"] },
  ],
  // Totalmente irregulares
  irregulares: [
    { inf: "être",    forms: ["suis", "es", "est", "sommes", "êtes", "sont"] },
    { inf: "avoir",   forms: ["ai", "as", "a", "avons", "avez", "ont"] },
    { inf: "aller",   forms: ["vais", "vas", "va", "allons", "allez", "vont"] },
    { inf: "faire",   forms: ["fais", "fais", "fait", "faisons", "faites", "font"] },
    { inf: "pouvoir", forms: ["peux", "peux", "peut", "pouvons", "pouvez", "peuvent"] },
    { inf: "savoir",  forms: ["sais", "sais", "sait", "savons", "savez", "savent"] },
    { inf: "vouloir", forms: ["veux", "veux", "veut", "voulons", "voulez", "veulent"] },
    { inf: "dire",    forms: ["dis", "dis", "dit", "disons", "dites", "disent"] },
    { inf: "lire",    forms: ["lis", "lis", "lit", "lisons", "lisez", "lisent"] },
    { inf: "écrire",  forms: ["écris", "écris", "écrit", "écrivons", "écrivez", "écrivent"] },
    { inf: "mettre",  forms: ["mets", "mets", "met", "mettons", "mettez", "mettent"] },
    { inf: "connaître", forms: ["connais", "connais", "connaît", "connaissons", "connaissez", "connaissent"] },
  ],
};

// Disparadores (déclencheurs) del subjonctif, agrupados por categoría
const SUBJ_TRIGGERS = {
  obligation: [
    { fr: "il faut que", es: "hay que / es necesario que" },
    { fr: "il est nécessaire que", es: "es necesario que" },
    { fr: "il est important que", es: "es importante que" },
    { fr: "il est urgent que", es: "es urgente que" },
    { fr: "il est essentiel que", es: "es esencial que" },
    { fr: "il est obligatoire que", es: "es obligatorio que" },
    { fr: "il est interdit que", es: "está prohibido que" },
    { fr: "il vaut mieux que", es: "es mejor que" },
  ],
  volonte: [
    { fr: "vouloir que", es: "querer que" },
    { fr: "souhaiter que", es: "desear que" },
    { fr: "aimer que", es: "gustar que" },
    { fr: "préférer que", es: "preferir que" },
    { fr: "exiger que", es: "exigir que" },
    { fr: "demander que", es: "pedir que" },
    { fr: "ordonner que", es: "ordenar que" },
    { fr: "interdire que", es: "prohibir que" },
  ],
  emotion: [
    { fr: "être content(e) que", es: "estar contento de que" },
    { fr: "être heureux/heureuse que", es: "estar feliz de que" },
    { fr: "être triste que", es: "estar triste de que" },
    { fr: "être surpris(e) que", es: "estar sorprendido de que" },
    { fr: "avoir peur que", es: "tener miedo de que" },
    { fr: "regretter que", es: "lamentar que" },
    { fr: "être désolé(e) que", es: "lamentar que" },
    { fr: "c'est dommage que", es: "es una pena que" },
  ],
  doute: [
    { fr: "douter que", es: "dudar que" },
    { fr: "ne pas penser que", es: "no pensar que" },
    { fr: "ne pas croire que", es: "no creer que" },
    { fr: "ne pas être sûr(e) que", es: "no estar seguro de que" },
    { fr: "il n'est pas certain que", es: "no es seguro que" },
    { fr: "il est possible que", es: "es posible que" },
    { fr: "il se peut que", es: "puede ser que" },
    { fr: "il est peu probable que", es: "es poco probable que" },
  ],
  conjonctions: [
    { fr: "pour que", es: "para que" },
    { fr: "afin que", es: "a fin de que" },
    { fr: "avant que", es: "antes de que" },
    { fr: "bien que", es: "aunque" },
    { fr: "quoique", es: "aunque" },
    { fr: "à condition que", es: "a condición de que" },
    { fr: "à moins que", es: "a menos que" },
    { fr: "jusqu'à ce que", es: "hasta que" },
    { fr: "sans que", es: "sin que" },
  ],
};

// Disparadores que NO llevan subjuntivo (para discriminación)
const INDIC_TRIGGERS = [
  { fr: "je pense que", es: "pienso que (afirmativo → indicativo)" },
  { fr: "je crois que", es: "creo que (afirmativo → indicativo)" },
  { fr: "je sais que", es: "sé que" },
  { fr: "il est certain que", es: "es seguro que" },
  { fr: "il est sûr que", es: "es seguro que" },
  { fr: "il est évident que", es: "es evidente que" },
  { fr: "il est vrai que", es: "es verdad que" },
  { fr: "il est probable que", es: "es probable que (¡ojo! con indicativo)" },
  { fr: "parce que", es: "porque" },
  { fr: "puisque", es: "puesto que" },
  { fr: "après que", es: "después de que" },
  { fr: "pendant que", es: "mientras" },
];

// Ejercicio: ¿subjuntivo o indicativo? Identificar el modo por el disparador
const MODE_CHOICE = [
  { sentence: "Il faut que tu ___ (venir) avec moi.", mode: "subj", answer: "viennes", trigger: "il faut que" },
  { sentence: "Je pense que tu ___ (avoir) raison.", mode: "indic", answer: "as", trigger: "je pense que" },
  { sentence: "Je veux que vous ___ (être) à l'heure.", mode: "subj", answer: "soyez", trigger: "vouloir que" },
  { sentence: "Il est évident qu'il ___ (être) fatigué.", mode: "indic", answer: "est", trigger: "il est évident que" },
  { sentence: "Bien qu'il ___ (faire) froid, je sors.", mode: "subj", answer: "fasse", trigger: "bien que" },
  { sentence: "Parce qu'elle ___ (être) malade, elle reste à la maison.", mode: "indic", answer: "est", trigger: "parce que" },
  { sentence: "J'ai peur qu'il ne ___ (pouvoir) pas venir.", mode: "subj", answer: "puisse", trigger: "avoir peur que" },
  { sentence: "Je sais qu'elle ___ (savoir) la vérité.", mode: "indic", answer: "sait", trigger: "je sais que" },
  { sentence: "Pour que les animaux ___ (vivre) en sécurité, agissons !", mode: "subj", answer: "vivent", trigger: "pour que" },
  { sentence: "Il est sûr que nous ___ (pouvoir) réussir.", mode: "indic", answer: "pouvons", trigger: "il est sûr que" },
  { sentence: "Je doute qu'ils ___ (avoir) raison.", mode: "subj", answer: "aient", trigger: "douter que" },
  { sentence: "Je crois qu'il ___ (faire) beau demain.", mode: "indic", answer: "fera / fait", trigger: "je crois que (afirm.)" },
  { sentence: "Il est possible qu'elle ___ (venir) demain.", mode: "subj", answer: "vienne", trigger: "il est possible que" },
  { sentence: "Avant que tu ___ (partir), appelle-moi.", mode: "subj", answer: "partes", trigger: "avant que" },
  { sentence: "Je ne pense pas que ce ___ (être) une bonne idée.", mode: "subj", answer: "soit", trigger: "ne pas penser que" },
  { sentence: "Il est vrai que les animaux ___ (souffrir) souvent.", mode: "indic", answer: "souffrent", trigger: "il est vrai que" },
  { sentence: "Je suis content que tu ___ (être) là.", mode: "subj", answer: "sois", trigger: "être content que" },
  { sentence: "C'est dommage qu'il ___ (pleuvoir).", mode: "subj", answer: "pleuve", trigger: "c'est dommage que" },
  { sentence: "Il est urgent que nous ___ (agir) contre la maltraitance.", mode: "subj", answer: "agissions", trigger: "il est urgent que" },
  { sentence: "Pendant que tu ___ (dormir), je travaille.", mode: "indic", answer: "dors", trigger: "pendant que" },
];

// Reformulación: transformar inf → subj (cambio de sujeto)
// `accepts` = lista completa de respuestas válidas. La primera es la canónica.
const TRANSFORM_SUBJ = [
  { from: "Il faut protéger les animaux.", to: "tu",
    accepts: ["Il faut que tu protèges les animaux."] },
  { from: "Il est nécessaire d'agir.", to: "nous",
    accepts: ["Il est nécessaire que nous agissions."] },
  { from: "Je veux adopter un chien.", to: "tu",
    accepts: ["Je veux que tu adoptes un chien."] },
  { from: "Il faut faire un don.", to: "vous",
    accepts: ["Il faut que vous fassiez un don."] },
  { from: "Il est urgent de sauver cette espèce.", to: "nous",
    accepts: ["Il est urgent que nous sauvions cette espèce."] },
  { from: "Il est important de sensibiliser les gens.", to: "on",
    accepts: ["Il est important qu'on sensibilise les gens."] },
  { from: "Il faut être responsable.", to: "ils",
    accepts: ["Il faut qu'ils soient responsables."] },
  { from: "Il est nécessaire d'avoir un refuge.", to: "elle",
    accepts: ["Il est nécessaire qu'elle ait un refuge."] },
];

// Traducciones ES → FR enfocadas en subjuntivo / obligación / interdicción / ne…que
// `accepts` = lista de variantes aceptables (puntuación final opcional, sinónimos comunes).
const TRANSLATE_GRAMMAR = [
  { es: "Hay que proteger a los animales.",
    accepts: ["Il faut protéger les animaux.", "On doit protéger les animaux.", "Nous devons protéger les animaux."] },
  { es: "Es necesario que tú adoptes un animal.",
    accepts: ["Il est nécessaire que tu adoptes un animal.", "Il faut que tu adoptes un animal."] },
  { es: "Está prohibido maltratar a los animales.",
    accepts: ["Il est interdit de maltraiter les animaux.", "C'est interdit de maltraiter les animaux."] },
  { es: "No hay que abandonar a los animales.",
    accepts: ["Il ne faut pas abandonner les animaux.", "On ne doit pas abandonner les animaux."] },
  { es: "Es urgente que actuemos.",
    accepts: ["Il est urgent que nous agissions.", "Il faut que nous agissions tout de suite."] },
  { es: "Debemos cuidar a los animales.",
    accepts: ["Nous devons soigner les animaux.", "On doit soigner les animaux.", "Il faut soigner les animaux."] },
  { es: "Quiero que seas voluntario en un refugio.",
    accepts: ["Je veux que tu sois bénévole dans un refuge.", "Je veux que tu sois bénévole au refuge."] },
  { es: "Es importante que nosotros hagamos una donación.",
    accepts: ["Il est important que nous fassions un don.", "C'est important que nous fassions un don."] },
  { es: "Tengo miedo de que esta especie desaparezca.",
    accepts: ["J'ai peur que cette espèce disparaisse.", "J'ai peur que cette espèce ne disparaisse."] },
  { es: "Aunque haga frío, vamos al refugio.",
    accepts: ["Bien qu'il fasse froid, nous allons au refuge.", "Bien qu'il fasse froid, on va au refuge.", "Quoiqu'il fasse froid, nous allons au refuge."] },
  { es: "Solo como verduras.",
    accepts: ["Je ne mange que des légumes."] },
  { es: "Solo tenemos un planeta.",
    accepts: ["Nous n'avons qu'une planète.", "On n'a qu'une planète."] },
  { es: "No hay que pegar a los animales.",
    accepts: ["Il ne faut pas battre les animaux.", "On ne doit pas battre les animaux."] },
  { es: "Es obligatorio vacunar a tu perro.",
    accepts: ["Il est obligatoire de vacciner ton chien.", "Il faut vacciner ton chien."] },
  { es: "No maltrates a los animales.",
    accepts: ["Ne maltraite pas les animaux.", "Il ne faut pas maltraiter les animaux."] },
  { es: "Para que los animales sean felices, hay que cuidarlos.",
    accepts: ["Pour que les animaux soient heureux, il faut les soigner.", "Pour que les animaux soient heureux, on doit les soigner."] },
];

// Ejercicios de gramática para el examen y la sección de subjuntivo
const GRAMMAR_EXERCISES = {
  neQue: [
    { fr: "Je mange seulement des légumes.", accepts: ["Je ne mange que des légumes."] },
    { fr: "Il y a seulement une solution.",  accepts: ["Il n'y a qu'une solution."] },
    { fr: "Nous adoptons seulement des chiens.", accepts: ["Nous n'adoptons que des chiens."] },
    { fr: "Tu bois seulement de l'eau.", accepts: ["Tu ne bois que de l'eau."] },
    { fr: "Elle aime seulement les chats.", accepts: ["Elle n'aime que les chats."] },
    { fr: "Ils protègent seulement les espèces en danger.", accepts: ["Ils ne protègent que les espèces en danger."] },
    { fr: "Je veux seulement t'aider.", accepts: ["Je ne veux que t'aider."] },
    { fr: "Il pense seulement à lui-même.", accepts: ["Il ne pense qu'à lui-même."] },
    { fr: "Nous avons seulement deux jours.", accepts: ["Nous n'avons que deux jours."] },
    { fr: "Elle parle seulement français.", accepts: ["Elle ne parle que français."] },
  ],
  obligation: TRANSLATE_GRAMMAR.slice(0, 10),
  subjonctif: [
    { prompt: "Il faut que nous (protéger) les animaux.", answer: "protégions" },
    { prompt: "Il est urgent que tu (agir) maintenant.", answer: "agisses" },
    { prompt: "Je veux que vous (être) responsables.", answer: "soyez" },
    { prompt: "Il faut qu'elle (faire) un don.", answer: "fasse" },
    { prompt: "Il est nécessaire qu'ils (avoir) un refuge.", answer: "aient" },
    { prompt: "Je souhaite que nous (pouvoir) sauver cette espèce.", answer: "puissions" },
    { prompt: "Il faut que tu (savoir) la vérité.", answer: "saches" },
    { prompt: "Il est important qu'on (adopter) au lieu d'acheter.", answer: "adopte" },
    { prompt: "Pour que les animaux (vivre) bien, agissons.", answer: "vivent" },
    { prompt: "Avant que tu (partir), nourris le chat.", answer: "partes" },
    { prompt: "Bien qu'il (faire) froid, je sors promener le chien.", answer: "fasse" },
    { prompt: "Je doute qu'ils (venir) au refuge.", answer: "viennent" },
    { prompt: "Il vaut mieux que vous (prendre) un taxi.", answer: "preniez" },
    { prompt: "C'est dommage que tu ne (vouloir) pas adopter.", answer: "veuilles" },
  ],
  modeChoice: MODE_CHOICE,
  transform: TRANSFORM_SUBJ,
  translate: TRANSLATE_GRAMMAR,
};
